sudo: required
dist: xenial
language: php
php:
  - '7.3'

before_install:
  - ./build/install_dependencies_ubuntu.sh
#  - echo "extension=sqlite3.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - echo "extension=pdo_sqlite.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
# do not build the entire solution; there are windows projects included
#  - dotnet build ./Peachpie.sln

# build projects we need:
  - dotnet pack ./src/Peachpie.App/ -f netstandard2.0
  - dotnet pack ./src/PDO/Peachpie.Library.PDO.Sqlite/
  - dotnet pack ./src/Peachpie.NET.Sdk/
  - dotnet build ./tests -c Release

# install nugets to nuget cache, and build the tests project
  - dotnet restore ./build/dummy

script:
  - dotnet test ./src/Tests/Peachpie.Runtime.Tests/Peachpie.Runtime.Tests.csproj
  - dotnet test ./src/Tests/Peachpie.DiagnosticTests/Peachpie.DiagnosticTests.csproj
  - ./build/runtests.sh
