sudo: required
dist: xenial
language: php
php:
  - '7.3'

before_install:
#  - echo "extension=pdo_sqlite.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - ./build/install_dependencies_ubuntu.sh
  - dotnet build ./Peachpie.sln -r ubuntu.16.04-x64
  - dotnet restore ./build/dummy
  - dotnet restore ./src/Tests/Peachpie.DiagnosticTests/
  - dotnet build ./tests -c Release

script:
  - dotnet test ./src/Tests/Peachpie.Runtime.Tests/Peachpie.Runtime.Tests.csproj
  - dotnet test ./src/Tests/Peachpie.DiagnosticTests/Peachpie.DiagnosticTests.csproj
  - ./build/runtests.sh
