sudo: required
dist: trusty
language: php
php:
  - '7.0'

install:
  - ./build/install_dependencies_ubuntu14.sh
  - powershell -File ./build/build.ps1 -suffix dev
  - powershell -File ./build/update-cache.ps1 0.6.0

script:
  - ./src/Tools/runtests_shell/runtests.sh
